databaseChangeLog:
  - changeSet:
      id: table_users_security
      author: vadblagiy@gmail.com
      preConditions:
        onFail: MARK_RAN
        not:
          tableExists:
            tableName: USERS
      changes:
        - createTable:
            tableName: USERS
            columns:
              - column:
                  name: USERNAME
                  type: VARCHAR(25)
                  constraints:
                    primaryKey: true
              - column:
                  name: PASSWORD
                  type: VARCHAR(50)
                  constraints:
                    nullable: false
              - column:
                  name: ENABLED
                  type: TINYINT(1)
  - changeSet:
      id: table_authorities_security
      author: vadblagiy@gmail.com
      preConditions:
        onFail: MARK_RAN
        not:
          tableExists:
            tableName: AUTHORITIES
      changes:
        - createTable:
            tableName: AUTHORITIES
            columns:
              - column:
                  name: USERNAME
                  type: VARCHAR(25)
                  constraints:
                    foreignKeyName: FK_USERNAME
                    references: USERS(USERNAME)
              - column:
                  name: AUTHORITY
                  type: VARCHAR(25)