databaseChangeLog:
  - changeSet:
      id: add-data-to-candidate-table
      author: Saranchuk Vadim
      changes:
        - sqlFile:
            dbms: mysql
            stripComments: true
            relativeToChangelogFile: true
            path: sql/add-some-data.sql